version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    commit-message:
      prefix: "MAINT"
    labels:
      - "maintenance"
  - package-ecosystem: pip
    directory: .github/constraints
    schedule:
      interval: daily
    cooldown:
      default-days: 7
    commit-message:
      prefix: "MAINT"
    labels:
      - "maintenance"
